spring:
  cloud:
    consul:
      host: localhost       # Adresse de Consul
      port: 8500            # Port par défaut de Consul
      discovery:
        service-name: SERVICE-CAR # Nom du service pour l'enregistrement dans Consul
  application:
    name: SERVICE-CAR
  datasource:
    url: jdbc:mysql://localhost:3306/carservicedb?createDatabaseIfNotExist=true
    username: root
    password:                 # Ajoutez ici votre mot de passe MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082   # Port d'exécution de l'application Client
